-- ============================================================
--  חשבונאוטיקה — Full Schema  (Plug & Play)
--  הדבק ב-Supabase SQL Editor והרץ בלחיצה אחת.
-- ============================================================


-- ────────────────────────────────────────────────────────────
-- 1. ניקוי — טריגר + פונקציה על auth.users (לפני DROP CASCADE)
-- ────────────────────────────────────────────────────────────
DROP TRIGGER  IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user()         CASCADE;

-- ────────────────────────────────────────────────────────────
-- 2. ניקוי — טבלאות (CASCADE מסיר Policies + Functions תלויות)
-- ────────────────────────────────────────────────────────────
DROP TABLE IF EXISTS public.coupons     CASCADE;
DROP TABLE IF EXISTS public.goals       CASCADE;
DROP TABLE IF EXISTS public.game_events CASCADE;
DROP TABLE IF EXISTS public.children    CASCADE;
DROP TABLE IF EXISTS public.profiles    CASCADE;

-- ────────────────────────────────────────────────────────────
-- 3. הרחבות
-- ────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ────────────────────────────────────────────────────────────
-- 4. טבלאות ליבה
-- ────────────────────────────────────────────────────────────

-- פרופיל הורה — נוצר אוטומטית עם הרישום (ראה טריגר בסעיף 7)
CREATE TABLE public.profiles (
  id                      UUID        PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  email                   TEXT        UNIQUE,
  subscription_status     TEXT        NOT NULL DEFAULT 'trial',   -- trial | active | vip | expired | canceled
  subscription_expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '14 days'),  -- 14 יום ניסיון
  applied_coupon          TEXT,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ילד — magic_token נוצר אוטומטית ב-DB (hex של 12 בתים = 24 תווים)
CREATE TABLE public.children (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_id   UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name        TEXT        NOT NULL,
  magic_token TEXT        UNIQUE NOT NULL DEFAULT encode(gen_random_bytes(12), 'hex'),
  avatar_url  TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- אירועי משחק — נכתב על ידי הילד בכל ניסיון (הצלחה / כישלון)
CREATE TABLE public.game_events (
  id          BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  child_token TEXT        NOT NULL,
  game_name   TEXT        NOT NULL,
  level       INTEGER     NOT NULL DEFAULT 1,
  success     BOOLEAN     NOT NULL DEFAULT false,
  data        JSONB,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- יעדי הורה (הסכמי פרסים) — target_hours אופציונלי לפרוגרס-בר הילד
CREATE TABLE public.goals (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_id    UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title        TEXT        NOT NULL,
  reward       TEXT        NOT NULL,
  target_hours INTEGER,                         -- אופציונלי: יעד שעות למידה
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- קופונים — duration_days=NULL → VIP ללא הגבלה
CREATE TABLE public.coupons (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  code          TEXT        UNIQUE NOT NULL,
  duration_days INTEGER,                        -- NULL = VIP / אינסוף
  description   TEXT,
  is_active     BOOLEAN     NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ────────────────────────────────────────────────────────────
-- 5. Row Level Security
-- ────────────────────────────────────────────────────────────
ALTER TABLE public.profiles    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.children    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.goals       ENABLE ROW LEVEL SECURITY;
-- coupons: ציבוריים לקריאה דרך RPC בלבד — אין RLS על הטבלה עצמה

-- profiles: הורה מנהל רק את הפרופיל שלו
CREATE POLICY "Users manage own profile"
  ON public.profiles FOR ALL
  USING (auth.uid() = id);

-- children: הורה מנהל רק את הילדים שלו
CREATE POLICY "Parents manage own children"
  ON public.children FOR ALL
  USING (auth.uid() = parent_id);

-- goals: הורה מנהל רק את היעדים שלו
CREATE POLICY "Parents manage own goals"
  ON public.goals FOR ALL
  USING (auth.uid() = parent_id);

-- game_events — קריאה: הורה רואה רק אירועים של ילדיו
CREATE POLICY "Parents view own children events"
  ON public.game_events FOR SELECT
  USING (
    child_token IN (
      SELECT magic_token FROM public.children
      WHERE parent_id = auth.uid()
    )
  );

-- game_events — כתיבה: כל טוקן תקף יכול להכניס (ילד משחק)
-- האימות האמיתי נעשה ב-RPC; כאן פותחים INSERT לציבור (anon)
CREATE POLICY "Child insert own events"
  ON public.game_events FOR INSERT
  WITH CHECK (true);

-- ────────────────────────────────────────────────────────────
-- 6. פונקציות RPC (SECURITY DEFINER — עוקפות RLS בבטחה)
-- ────────────────────────────────────────────────────────────

-- 6א. בדיקת סטטוס מנוי לפי magic_token של הילד
CREATE OR REPLACE FUNCTION public.get_child_subscription(p_token TEXT)
RETURNS TABLE(
  subscription_status     TEXT,
  subscription_expires_at TIMESTAMPTZ
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p.subscription_status,
         p.subscription_expires_at
  FROM   public.children  c
  JOIN   public.profiles  p ON p.id = c.parent_id
  WHERE  c.magic_token = p_token
  LIMIT  1;
$$;

-- 6ב. היסטוריית אירועי משחק לפי magic_token של הילד (200 אחרונים)
CREATE OR REPLACE FUNCTION public.get_child_events(p_token TEXT)
RETURNS SETOF public.game_events
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT *
  FROM   public.game_events
  WHERE  child_token = p_token
  ORDER  BY created_at DESC
  LIMIT  200;
$$;

-- 6ג. יעדי הורה (title, reward, target_hours) לפי magic_token של הילד
CREATE OR REPLACE FUNCTION public.get_child_goals(p_token TEXT)
RETURNS TABLE(
  id           UUID,
  parent_id    UUID,
  title        TEXT,
  reward       TEXT,
  target_hours INTEGER,
  created_at   TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_parent_id UUID;
BEGIN
  -- מצא את ה-parent_id מתוך הטוקן
  SELECT c.parent_id INTO v_parent_id
  FROM   public.children c
  WHERE  c.magic_token = p_token
  LIMIT  1;

  -- טוקן לא קיים → החזר טבלה ריקה
  IF v_parent_id IS NULL THEN
    RETURN;
  END IF;

  RETURN QUERY
    SELECT g.id, g.parent_id, g.title, g.reward, g.target_hours, g.created_at
    FROM   public.goals g
    WHERE  g.parent_id = v_parent_id
    ORDER  BY g.created_at DESC;
END;
$$;

-- 6ד. מימוש קופון — מחייב משתמש מחובר (auth.uid() חייב להיות קיים)
CREATE OR REPLACE FUNCTION public.apply_coupon(p_code TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_days    INTEGER;
  v_active  BOOLEAN;
BEGIN
  -- בדוק אם הקוד קיים ופעיל
  SELECT is_active, duration_days
  INTO   v_active, v_days
  FROM   public.coupons
  WHERE  code = UPPER(TRIM(p_code));

  IF NOT FOUND OR NOT v_active THEN
    RETURN 'invalid';
  END IF;

  -- עדכן את פרופיל המשתמש המחובר
  UPDATE public.profiles
  SET
    subscription_status     = CASE WHEN v_days IS NULL THEN 'vip' ELSE 'active' END,
    subscription_expires_at = CASE
                                WHEN v_days IS NULL THEN NOW() + INTERVAL '100 years'
                                ELSE NOW() + (v_days || ' days')::INTERVAL
                              END,
    applied_coupon          = UPPER(TRIM(p_code))
  WHERE id = auth.uid();

  -- אם auth.uid() לא מצא שורה → משתמש לא מחובר
  IF NOT FOUND THEN
    RETURN 'unauthorized';
  END IF;

  RETURN 'success';
END;
$$;

-- הרשאות EXECUTE לפונקציות (anon = ילד; authenticated = הורה)
GRANT EXECUTE ON FUNCTION public.get_child_subscription(TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_child_events(TEXT)        TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_child_goals(TEXT)         TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.apply_coupon(TEXT)            TO authenticated;

-- ────────────────────────────────────────────────────────────
-- 7. טריגר — יצירת פרופיל אוטומטי בהרשמה (14 יום ניסיון)
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, subscription_status, subscription_expires_at)
  VALUES (
    NEW.id,
    NEW.email,
    'trial',
    NOW() + INTERVAL '14 days'
  )
  ON CONFLICT (id) DO NOTHING;   -- מגן מפני הרצה כפולה
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_new_user();

-- ────────────────────────────────────────────────────────────
-- 8. נתונים ראשוניים — קופונים
-- ────────────────────────────────────────────────────────────
INSERT INTO public.coupons (code, duration_days, description) VALUES
  ('GIFT30',     30,   'חודש מתנה'),
  ('GIFT60',     60,   'חודשיים מתנה'),
  ('MASTER-VIP', NULL, 'גישה VIP ללא הגבלת זמן')
ON CONFLICT (code) DO NOTHING;   -- בטוח להרצה חוזרת

-- ============================================================
-- ✅ Schema מוכן.
-- לאחר הרצה, ודא ב-Supabase Dashboard:
--   Table Editor → profiles / children / game_events / goals / coupons
--   Database → Functions → 4 פונקציות קיימות
--   Database → Triggers → on_auth_user_created על auth.users
-- ============================================================
