-- ============================================================
--  Migration 05 — Admin Operations (Overwatch Command Center)
--  audit_log + admin_approve_teacher + admin_revoke_teacher
--  + admin_set_subscription + admin_view_* (read-only RPCs).
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- 1. audit_log
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.audit_log (
  id             BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  admin_id       UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  admin_email    TEXT,
  action         TEXT        NOT NULL,  -- 'approve_teacher' | 'revoke_teacher' | 'manual_subscription_change' | 'manual_coupon_grant'
  target_user_id UUID,
  target_email   TEXT,
  payload        JSONB,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS audit_log_created_idx ON public.audit_log (created_at DESC);

ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admin reads audit" ON public.audit_log;
CREATE POLICY "Admin reads audit"
  ON public.audit_log FOR SELECT
  USING (public.is_admin_caller());

-- ────────────────────────────────────────────────────────────
-- 2. admin_approve_teacher(email)
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_approve_teacher(p_email TEXT)
RETURNS TABLE(user_id UUID, classroom_code TEXT, email TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user  public.profiles%ROWTYPE;
  v_code  TEXT;
  v_admin UUID := auth.uid();
  v_admin_email TEXT;
BEGIN
  IF NOT public.is_admin_caller() THEN
    RAISE EXCEPTION 'not_authorized';
  END IF;

  SELECT email INTO v_admin_email FROM public.profiles WHERE id = v_admin;

  SELECT * INTO v_user
  FROM   public.profiles
  WHERE  LOWER(email) = LOWER(TRIM(p_email))
  LIMIT  1;

  IF v_user.id IS NULL THEN
    RAISE EXCEPTION 'user_not_found';
  END IF;

  -- צור classroom_code ייחודי (6 תווים)
  LOOP
    v_code := UPPER(SUBSTRING(ENCODE(gen_random_bytes(3), 'hex') FROM 1 FOR 6));
    EXIT WHEN NOT EXISTS (SELECT 1 FROM public.profiles WHERE classroom_code = v_code);
  END LOOP;

  UPDATE public.profiles
  SET    role                    = 'teacher',
         is_approved             = true,
         teacher_status          = 'approved',
         classroom_code          = v_code,
         max_children_allowed    = GREATEST(max_children_allowed, 40),
         subscription_status     = 'active',
         subscription_expires_at = NOW() + INTERVAL '1 year'
  WHERE  id = v_user.id;

  -- סמן את כל הלידים של המייל הזה כטופלו
  UPDATE public.teacher_leads
  SET    handled = true
  WHERE  LOWER(email) = LOWER(v_user.email) AND handled = false;

  INSERT INTO public.audit_log (admin_id, admin_email, action, target_user_id, target_email, payload)
  VALUES (v_admin, v_admin_email, 'approve_teacher', v_user.id, v_user.email,
          jsonb_build_object('classroom_code', v_code));

  user_id        := v_user.id;
  classroom_code := v_code;
  email          := v_user.email;
  RETURN NEXT;
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_approve_teacher(TEXT) TO authenticated;

-- ────────────────────────────────────────────────────────────
-- 3. admin_revoke_teacher(user_id)
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_revoke_teacher(p_user_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_admin UUID := auth.uid();
  v_admin_email TEXT;
  v_target_email TEXT;
BEGIN
  IF NOT public.is_admin_caller() THEN
    RAISE EXCEPTION 'not_authorized';
  END IF;

  SELECT email INTO v_admin_email FROM public.profiles WHERE id = v_admin;
  SELECT email INTO v_target_email FROM public.profiles WHERE id = p_user_id;

  UPDATE public.profiles
  SET    role           = 'parent',
         is_approved    = true,
         teacher_status = NULL,
         classroom_code = NULL
  WHERE  id = p_user_id;

  INSERT INTO public.audit_log (admin_id, admin_email, action, target_user_id, target_email)
  VALUES (v_admin, v_admin_email, 'revoke_teacher', p_user_id, v_target_email);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_revoke_teacher(UUID) TO authenticated;

-- ────────────────────────────────────────────────────────────
-- 4. admin_set_subscription(user_id, status, expires_at, coupon)
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_set_subscription(
  p_user_id    UUID,
  p_status     TEXT,
  p_expires_at TIMESTAMPTZ,
  p_coupon     TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_admin UUID := auth.uid();
  v_admin_email TEXT;
  v_target_email TEXT;
  v_action TEXT;
BEGIN
  IF NOT public.is_admin_caller() THEN
    RAISE EXCEPTION 'not_authorized';
  END IF;

  SELECT email INTO v_admin_email  FROM public.profiles WHERE id = v_admin;
  SELECT email INTO v_target_email FROM public.profiles WHERE id = p_user_id;

  UPDATE public.profiles
  SET    subscription_status     = COALESCE(p_status,     subscription_status),
         subscription_expires_at = COALESCE(p_expires_at, subscription_expires_at),
         applied_coupon          = COALESCE(p_coupon,     applied_coupon)
  WHERE  id = p_user_id;

  v_action := CASE WHEN p_coupon IS NOT NULL THEN 'manual_coupon_grant' ELSE 'manual_subscription_change' END;

  INSERT INTO public.audit_log (admin_id, admin_email, action, target_user_id, target_email, payload)
  VALUES (v_admin, v_admin_email, v_action, p_user_id, v_target_email,
          jsonb_build_object('status', p_status, 'expires_at', p_expires_at, 'coupon', p_coupon));
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_set_subscription(UUID, TEXT, TIMESTAMPTZ, TEXT) TO authenticated;

-- ────────────────────────────────────────────────────────────
-- 5. admin_view_parent_dashboard(user_id) — Overwatch read-only
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_view_parent_dashboard(p_user_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_profile JSONB;
  v_child   JSONB;
  v_events  JSONB;
  v_goals   JSONB;
BEGIN
  IF NOT public.is_admin_caller() THEN
    RAISE EXCEPTION 'not_authorized';
  END IF;

  SELECT to_jsonb(p) INTO v_profile FROM public.profiles p WHERE p.id = p_user_id;

  SELECT to_jsonb(c) INTO v_child
  FROM   public.children c
  WHERE  c.parent_id = p_user_id
  ORDER  BY c.created_at ASC
  LIMIT  1;

  SELECT COALESCE(jsonb_agg(to_jsonb(e) ORDER BY e.created_at DESC), '[]'::jsonb) INTO v_events
  FROM (
    SELECT * FROM public.game_events
    WHERE  child_token = (SELECT magic_token FROM public.children WHERE parent_id = p_user_id ORDER BY created_at ASC LIMIT 1)
    ORDER  BY created_at DESC
    LIMIT  200
  ) e;

  SELECT COALESCE(jsonb_agg(to_jsonb(g) ORDER BY g.created_at ASC), '[]'::jsonb) INTO v_goals
  FROM   public.goals g
  WHERE  g.parent_id = p_user_id;

  RETURN jsonb_build_object(
    'profile', v_profile,
    'child',   v_child,
    'events',  v_events,
    'goals',   v_goals
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_view_parent_dashboard(UUID) TO authenticated;

-- ────────────────────────────────────────────────────────────
-- 6. admin_view_teacher_dashboard(user_id) — Overwatch read-only
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_view_teacher_dashboard(p_user_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_profile     JSONB;
  v_students    JSONB;
  v_events      JSONB;
  v_assignments JSONB;
BEGIN
  IF NOT public.is_admin_caller() THEN
    RAISE EXCEPTION 'not_authorized';
  END IF;

  SELECT to_jsonb(p) INTO v_profile FROM public.profiles p WHERE p.id = p_user_id;

  SELECT COALESCE(jsonb_agg(to_jsonb(s) ORDER BY s.created_at DESC), '[]'::jsonb) INTO v_students
  FROM   public.get_teacher_class_overview(p_user_id) s;

  SELECT COALESCE(jsonb_agg(to_jsonb(e) ORDER BY e.created_at DESC), '[]'::jsonb) INTO v_events
  FROM (
    SELECT *
    FROM   public.game_events
    WHERE  child_token IN (SELECT magic_token FROM public.children WHERE teacher_id = p_user_id)
    ORDER  BY created_at DESC
    LIMIT  500
  ) e;

  SELECT COALESCE(jsonb_agg(to_jsonb(a) ORDER BY a.created_at DESC), '[]'::jsonb) INTO v_assignments
  FROM   public.assignments a
  WHERE  a.teacher_id = p_user_id;

  RETURN jsonb_build_object(
    'profile',     v_profile,
    'students',    v_students,
    'events',      v_events,
    'assignments', v_assignments
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_view_teacher_dashboard(UUID) TO authenticated;

-- ────────────────────────────────────────────────────────────
-- 7. admin_list_users — רשימה לחיפוש ב-UsersTab
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_list_users(p_search TEXT DEFAULT NULL)
RETURNS TABLE(
  id                      UUID,
  email                   TEXT,
  role                    TEXT,
  is_approved             BOOLEAN,
  is_admin                BOOLEAN,
  subscription_status     TEXT,
  subscription_expires_at TIMESTAMPTZ,
  classroom_code          TEXT,
  applied_coupon          TEXT,
  created_at              TIMESTAMPTZ
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin_caller() THEN
    RAISE EXCEPTION 'not_authorized';
  END IF;
  RETURN QUERY
    SELECT p.id, p.email, p.role, p.is_approved, p.is_admin,
           p.subscription_status, p.subscription_expires_at,
           p.classroom_code, p.applied_coupon, p.created_at
    FROM   public.profiles p
    WHERE  p_search IS NULL
        OR p.email ILIKE '%' || p_search || '%'
    ORDER  BY p.created_at DESC
    LIMIT  500;
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_list_users(TEXT) TO authenticated;

-- ============================================================
-- ✅ Migration 05 הושלם.
-- ============================================================
