import { useState } from 'react';
import { Plus, X } from 'lucide-react';

/**
 * Inline form to add a new student. On success, parent component
 * receives the access_code generated by the DB.
 *
 * Props:
 *  onAdd    – (name) => Promise<student|null>
 *  disabled – boolean (e.g. when at max_children_allowed)
 */
export default function AddStudentForm({ onAdd, disabled }) {
  const [open, setOpen]       = useState(false);
  const [name, setName]       = useState('');
  const [saving, setSaving]   = useState(false);
  const [error, setError]     = useState('');
  const [justAdded, setJustAdded] = useState(null);

  async function submit(e) {
    e.preventDefault();
    setError('');
    if (!name.trim()) { setError('הזן שם תלמיד'); return; }
    setSaving(true);
    try {
      const student = await onAdd(name.trim());
      if (student) {
        setJustAdded(student);
        setName('');
      }
    } catch (err) {
      setError(err?.message || 'שגיאה בהוספה');
    } finally {
      setSaving(false);
    }
  }

  if (disabled) {
    return (
      <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 text-center">
        <p className="text-sm font-bold text-amber-800">הגעת למגבלת התלמידים בתכנית שלך</p>
      </div>
    );
  }

  if (!open && !justAdded) {
    return (
      <button
        onClick={() => setOpen(true)}
        className="w-full flex items-center justify-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-black py-3 px-6 rounded-2xl transition-all active:scale-95"
      >
        <Plus size={18} /> הוסף תלמיד
      </button>
    );
  }

  if (justAdded) {
    return (
      <div className="bg-green-50 border-2 border-green-200 rounded-2xl p-5 space-y-3">
        <div className="flex items-center justify-between">
          <p className="text-sm font-black text-green-800">✅ {justAdded.name} נוסף לכיתה</p>
          <button onClick={() => setJustAdded(null)} className="text-green-600 hover:text-green-800"><X size={16} /></button>
        </div>
        <div className="bg-white rounded-xl p-4 border border-green-100">
          <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">קוד כניסה של {justAdded.name}</p>
          <p className="text-2xl font-black font-mono tracking-widest text-indigo-700 select-all">{justAdded.access_code}</p>
          <p className="text-xs text-slate-500 mt-2">שלח לתלמיד — הוא יזין את הקוד במסך הכניסה ויתחיל לשחק.</p>
        </div>
        <button
          onClick={() => { setJustAdded(null); setOpen(true); }}
          className="w-full text-sm font-bold text-indigo-600 hover:text-indigo-700"
        >
          + הוסף תלמיד נוסף
        </button>
      </div>
    );
  }

  return (
    <form onSubmit={submit} className="bg-white border-2 border-indigo-200 rounded-2xl p-5 space-y-3">
      <h4 className="text-sm font-black text-slate-700">הוספת תלמיד לכיתה</h4>
      <input
        autoFocus
        className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-300"
        placeholder="שם התלמיד (חובה)"
        value={name}
        onChange={e => { setName(e.target.value); setError(''); }}
      />
      {error && <p className="text-xs text-red-500 font-bold">{error}</p>}
      <div className="flex gap-2">
        <button
          type="submit"
          disabled={saving}
          className="flex-1 bg-indigo-600 hover:bg-indigo-700 disabled:opacity-60 text-white py-2.5 rounded-xl font-black text-sm active:scale-95 transition-all"
        >
          {saving ? '⏳ מוסיף...' : 'הוסף'}
        </button>
        <button
          type="button"
          onClick={() => { setOpen(false); setName(''); setError(''); }}
          className="px-4 py-2.5 text-slate-500 font-bold text-sm hover:text-slate-700"
        >
          ביטול
        </button>
      </div>
    </form>
  );
}
